export const equipmentLabelMap: Record<string, string> = {
    TV: "ทีวี",
    DesktopComputer: "คอมพิวเตอร์ตั้งโต๊ะ",
    Refrigerator: "ตู้เย็น",
    FloorFan: "พัดลมตั้งพื้น",
    LargeTV: "ทีวีจอใหญ่",
    AudioSystem: "เครื่องเสียง",
    Microwave: "ไมโครเวฟ",
    RiceCooker: "หม้อหุงข้าว",
    Printer: "เครื่องพิมพ์",
    POS: "เครื่องคิดเงิน POS",
    ElectricOvenStove: "เตาอบไฟฟ้า",
    Projector: "โปรเจคเตอร์",
    TVMonitor: "จอมอนิเตอร์",
    Laptop: "โน้ตบุ๊ก",
    Speaker: "ลำโพง",
    Copier: "เครื่องถ่ายเอกสาร",
    RefrigeratorFreezer: "ตู้เย็น/ตู้แช่",
    CounterLight: "ไฟเคาน์เตอร์",
};
